apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: baseus-app 
  namespace: default
spec:   
  interval: 1m 
  chart:
    spec: 
      chart: ./baseus-web
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m